### ISSUE TITLE
implement remaining queue wrapper functions

### ISSUE THREAD

**Issue by J0sueTM** [moclojer/clj-rq#13]
As of now, we have wrapped the queue functions pop, push and llen. These are great to the extent of what we've been using `clj-rq` until now. However, in order to better expand the library into users outside of `moclojer`, we need to make sure to deliver a good wrapper with great coverage.

- [x] fork and build jedis with `-parameters` enabled
- [ ] use reflection to retrieve methods and transpose them to clj

**Comment by J0sueTM** [comment]
@avelino @Felipe-gsilva @matheusfrancisco  After tiring myself by trying to compile every redis function from Java to Clojure, I thought of the following:

All Jedis' functions are in [this file!(https://github.com/redis/jedis/blob/master/src/main/java/redis/clients/jedis/UnifiedJedis.java). What if we could just retrieve this file, and given any function, rebuild it in clojure based on the amount of parameters.

For example:

```java
  public long persist(String key) {
```

becomes, in our clojure file (probably by building everything with a big macro):

```clojure
(defn persist [client key]
  (.persist client key])
```

What do you guys think?

**Comment by avelino** [comment]
I like the idea and wrappers should be built this way, but with the possibility to customize the behavior of some specific function when necessary.

@J0sueTM do you have any idea how to implement this?

**Comment by J0sueTM** [comment]
I began scratching around with this idea last week. Basically, what we need to do is load the jedis repo as a submodule in our resources folder which should be cloned and read on development or build time.

After loading the file resource UnifiedJedis.java, we strip lines that begin with `public _ myFunction`. and transpose then afterwards to clojure function, transferring the function as said in my last comment.

We shall filter out non needed functions, or better yet just keep a list of the functions we need to be transpiled. I prefer using an allowlist, since a blocklist might be prejudicial in the future if a new function is added, and we as contributors forget to add it to the blocklist

We also need to keep a list of functions that have directions. For example push, which can be eitheir left or right.

So to pack it up:

1. Add the jedis repo as a submodule so the contents are only loaded when necessary
2. Load the UnifiedJedis.java file and strip out the lines that looks like a public function
3. Filter out blocked functions based on an internal allowed function list made by ourselves
4. Separate these functions between "directable" and "non-directable" (i.e. functions that can go either right or left, or no direction at all6.
5. Dump these functions within a macro, back at real code.
6. Of course test this thoroughly. I don;t trust macros that much :sweat_smile: (maybe there;s a way to do it without them :thinking: )

**Comment by avelino** [comment]
@J0sueTM check this project https://github.com/emlyn/tortilla

**Comment by Felipe-gsilva** [comment]
https://github.com/trptr/java-wrapper/blob/master/src/trptr/java_wrapper/locale.clj

this is a small wrapper built for  java.util.Locale, but maybe can have some interesting ideas for our use case.

**Comment by J0sueTM** [comment]
@avelino @Felipe-gsilva I was testing around and got pretty close to retrieving every method correctly. Actually I did:

```clojure
  (import [java.util Arrays])
  (require '[clojure.string :as str])

  (def my-client (create-client "redis://localhost:6379"))

  (->> (.. @my-client getClass getMethods)
       (take 10)
       (map
        (fn [class]
          {:name (.getName class)
           :parameters (map #(.getName %) (.getParameters class))}))
       (clojure.pprint/pprint))

;; =>


  ({:name "pipelined", :parameters ()}
   {:name "pipelined", :parameters ()}
   {:name "getPool", :parameters ()}
   {:name "executeCommand", :parameters ("arg0")}
   {:name "executeCommand", :parameters ("arg0")}
   {:name "broadcastCommand", :parameters ("arg0")}
   {:name "setBroadcastAndRoundRobinConfig", :parameters ("arg0")}
   {:name "ping", :parameters ()}
   {:name "flushDB", :parameters ()}
   {:name "flushAll", :parameters ()})
```

When compiling a java package, we lose the argnames, so we get these weird looking arg<number> parameters.

This is why I forked [jedis](https://github.com/moclojer/jedis), so we can build it ourselvel with the `-parameters` flag enabled, consequently being able to read these damn parameters.

**Comment by J0sueTM** [comment]
@avelino @Felipe-gsilva I've finished retrieving every function from the jedis source code and parsing them up. I just need to dump it all into the final source code.

Do you guys think that it would be best to keep the functions inside `queue.clj` or inside `core.clj`.

The main pro of putting into core.clj is that not all functions are about queues. And since it will all be generated in the fly, it feels better for the enduser to just include rq.core and use the functions dynamically loaded.

See the current HEAD at `feat/dynamic-queue-fns` for the source code I'm referring to.

**Comment by avelino** [comment]
@J0sueTM I like the edn implementation of the functions we need to map with the reflection 

I would make a function that receives the "type" (queue or pubsub), so I would have a specific edn for each "type" with the functions we need for it (queue or pubsub).

The function would be called within the namespace we want
